# Generated by Django 3.2.6 on 2021-08-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_books_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='books',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='pages',
            field=models.IntegerField(null=True),
        ),
    ]
