# Generated by Django 3.2.6 on 2021-08-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210814_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_file',
            field=models.FileField(null=True, upload_to='media/doc/'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
